services:
  mongo:
    image: mongo:6.0
    container_name: codevm-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: codevm
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: codevm-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongo:27017/codevm
      PORT: 5000
      JWT_SECRET: some_secret
      GOOGLE_GEMINI_API_KEY: ${GOOGLE_GEMINI_API_KEY}
      AI_REVIEW_API_URL: ${AI_REVIEW_API_URL}
      COMPILER_URL: http://codevm-compiler:9000
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules   # prevent node_modules overwrite

  compiler:
    build: ./compiler
    container_name: codevm-compiler
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      NODE_ENV: development
    depends_on:
      - mongo
    volumes:
      - ./compiler:/app
      - /app/node_modules   # prevent node_modules overwrite

  frontend:
    image: node:18-alpine
    container_name: codevm-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules   # prevent node_modules overwrite
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"
    environment:
      NODE_ENV: development
    depends_on:
      - backend
      - compiler

volumes:
  mongo_data:
