#!/bin/bash

# 🚀 Quick Deploy Script for EulerHub
# This script provides step-by-step deployment commands

echo "🚀 EulerHub Quick Deployment Guide"
echo "=================================="
echo ""

echo "📋 Step 1: Prepare Frontend for Netlify"
echo "----------------------------------------"
echo "cd frontend"
echo "npm install"
echo "npm run build"
echo ""

echo "📋 Step 2: Deploy to Netlify"
echo "-----------------------------"
echo "1. Go to netlify.com and login"
echo "2. Drag & drop the 'frontend/dist' folder"
echo "3. Set environment variables:"
echo "   VITE_SERVER=https://your-ec2-domain.com"
echo "   VITE_COMPILER=https://your-ec2-domain.com/compiler"
echo ""

echo "📋 Step 3: Deploy Backend to EC2"
echo "---------------------------------"
echo "ssh -i your-key.pem ubuntu@your-ec2-ip"
echo "sudo apt update && sudo apt upgrade -y"
echo "curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -"
echo "sudo apt-get install -y nodejs"
echo "sudo npm install -g pm2"
echo "sudo apt install -y nginx"
echo ""

echo "📋 Step 4: Clone and Setup Backend"
echo "-----------------------------------"
echo "git clone https://github.com/yourusername/eulerhub.git"
echo "cd eulerhub/backend"
echo "npm install"
echo ""

echo "📋 Step 5: Configure Backend Environment"
echo "----------------------------------------"
echo "Create .env file with:"
echo "MONGO_URI=mongodb+srv://username:password@cluster.mongodb.net/eulerhub"
echo "PORT=5000"
echo "JWT_SECRET=your-super-secret-jwt-key-here"
echo "GOOGLE_GEMINI_API_KEY=your-gemini-api-key"
echo "NODE_ENV=production"
echo ""

echo "📋 Step 6: Start Backend Service"
echo "--------------------------------"
echo "pm2 start server.js --name 'eulerhub-backend'"
echo "pm2 save"
echo "pm2 startup"
echo ""

echo "📋 Step 7: Setup Compiler Service"
echo "---------------------------------"
echo "cd ../compiler"
echo "npm install"
echo "pm2 start index.js --name 'eulerhub-compiler'"
echo "pm2 save"
echo ""

echo "📋 Step 8: Configure Nginx"
echo "---------------------------"
echo "Follow the Nginx configuration in DEPLOYMENT_GUIDE.md"
echo "sudo nginx -t"
echo "sudo systemctl restart nginx"
echo ""

echo "📋 Step 9: Setup SSL (Optional)"
echo "--------------------------------"
echo "sudo apt install -y certbot python3-certbot-nginx"
echo "sudo certbot --nginx -d your-ec2-domain.com"
echo ""

echo "📋 Step 10: Test Deployment"
echo "----------------------------"
echo "curl https://your-ec2-domain.com/api/problems"
echo "curl https://your-ec2-domain.com/compiler/health"
echo ""

echo "🎉 Deployment Complete!"
echo "======================"
echo "Frontend: https://your-netlify-app.netlify.app"
echo "Backend: https://your-ec2-domain.com"
echo ""

echo "📚 For detailed instructions, see DEPLOYMENT_GUIDE.md"
echo "🔧 For troubleshooting, check the logs with:"
echo "   pm2 logs"
echo "   sudo tail -f /var/log/nginx/error.log"
